### ISSUE TITLE
Change current action

### ISSUE THREAD

**Issue by ernst77** [jvitkauskas/homeassistant_blauberg_s21#1]
Hello,

Currently `hvac_action` is always `heating` despite the operation `mode` I select. Could we change it so it correlates with current mode? 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/17262977/218732929-e1f72455-8fe4-4c39-853c-e2e9f694fd54.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/17262977/218732537-3ae9274e-58f7-4475-9205-52cdbee2b6a7.png">

**Comment by jvitkauskas** [comment]
Maybe, I am not really sure when `HVACAction` should be `IDLE`. Right now I am comparing input and output temperatures to show what's happening, but maybe it's not the right idea. https://github.com/jvitkauskas/pybls21/blob/e1e3ef6d6356ef6cc45a756df9810ef302cdce72/pybls21/client.py#L109

**Comment by jvitkauskas** [comment]
Should be fixed now
