### ISSUE TITLE
Connection not possible on 2024.12.5

### ISSUE THREAD

**Issue by travismarius** [jvitkauskas/homeassistant_blauberg_s21#5]
I´ve just updated my environment to the following versions:
Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1
Frontend 20241127.8

After OS Update to 14.1 the connection to my Blauberg Unit is not possible anymore and I´m getting the following error:

![image](https://github.com/user-attachments/assets/d27fa6f4-69c4-450e-8c46-a7a5199257a7)

Regards,
Marius

**Comment by fototakas** [comment]
@travismarius Already fixed by Alen, delete this custom component and add new one pointing to Alen fork:
https://github.com/alenl2/homeassistant_blauberg_s21

**Comment by travismarius** [comment]
Hi @fototakas, thanks for that advice! Now it is working again!

regards,
travis
